### ISSUE TITLE
请问这几个repo是什么关系？

### ISSUE THREAD

**Issue by tomriddle1234** [itning/shw_server#1]
感谢这么好的作业管理系统，真是帮了大忙。

我发现除了shw_server以外还有个[Student-Homework-Management-System库](https://github.com/itning/Student-Homework-Management-System)
这两个repo是什么关系，shw_server文档看不太懂，请问有没有类似[Student-Homework-Management-System库](https://github.com/itning/Student-Homework-Management-System)的界面

**Comment by itning** [comment]
您好。[Student-Homework-Management-System](https://github.com/itning/Student-Homework-Management-System)使用的UI库是[Bootstrap 3](https://v3.bootcss.com/)

作业管理系统 每个repo都大同小异。
1. [shw_server](https://github.com/itning/shw_server/tree/master)使用spring boot开发
2. [shw_server v2](https://github.com/itning/shw_server)使用spring cloud开发
3. [Student-Homework-Management-System](https://github.com/itning/Student-Homework-Management-System)使用SSM进行开发
