### ISSUE TITLE
请问登录的账号和密码是什么？

### ISSUE THREAD

**Issue by watashiymy** [itning/shw_server#10]
不知道账号和密码无法登陆进入系统，也没提供用户注册的接口

**Comment by itning** [comment]
单点登录需要搭建单点登录服务器的

**Comment by watashiymy** [comment]
> 单点登录需要搭建单点登录服务器的

所以没办法登录进去看系统的完整功能吗😥

**Comment by itning** [comment]
嗯 或者 改源码也可以

**Comment by watashiymy** [comment]
> 嗯 或者 改源码也可以

我看源码，账户和密码分别是username和password，但是尝试了还是登不进去，是我找错地方了吗？可否指个路

**Comment by itning** [comment]
哪个分支？master 还是 V2 ？

**Comment by watashiymy** [comment]
> 哪个分支？master 还是 V2 ？

master

**Comment by itning** [comment]
https://github.com/itning/shw_server/blob/master/src/main/java/top/yunshu/shw/server/cas/CasConfigImpl.java#L25
https://github.com/itning/shw_server/blob/master/src/main/java/top/yunshu/shw/server/cas/JwtCasCallBackImpl.java
CAS库：
https://github.com/itning/cas-spring-boot-starter
