### ISSUE TITLE
jar包

### ISSUE THREAD

**Issue by in-my-heart** [itning/shw_server#7]
1、`<cas.spring.boot.starter.version>1.1.0-RELEASE</cas.spring.boot.starter.version>`
这个cas一直下载不下来
2、`set INSTALL_VERSION=1.0.0.RELEASE`  应该把RELEASE去掉，因为pom文件没有

**Comment by itning** [comment]
[源码链接](https://github.com/itning/cas-spring-boot-starter)

[1.1.0.RELEASE](https://github.com/itning/cas-spring-boot-starter/releases/tag/1.1.0-RELEASE)

哦哦 看了下 确实 我改下

**Comment by itning** [comment]
[OK了](https://github.com/itning/shw_server/commit/7513b8e7a5044af0c8668837016aa3231533d440)
