### ISSUE TITLE
运行

### ISSUE THREAD

**Issue by in-my-heart** [itning/shw_server#8]
小白问下这个username: ${env.MYSQL_USERNAME}
用户名密码等等这些哪里设置啊，是docker那个命令吗
我就win10+idea想运行看看效果，怎么弄呀。还有就是你的github上面所有图片都显示不出来。

**Comment by itning** [comment]
`${env.MYSQL_USERNAME}` 是取环境变量里的数据库用户名，你直接改成自己的就行。

github 显示不出来  你需要 科学上网
