### ISSUE TITLE
运行docker的时候出现warning

### ISSUE THREAD

**Issue by clowdy52** [itning/shw_server#9]
在服务器运行docker指令，出现warning：
` WARN 1 -- [gistrationTask1] d.c.b.a.c.r.ApplicationRegistrator       : Failed to register application as Application(name=SHW, managementUrl=http://8cef392b30ae:8080/config/actuator, healthUrl=http://8cef392b30ae:8080/config/actuator/health, serviceUrl=http://8cef392b30ae:8080/) at spring-boot-admin ([http://localhost:8888/instances]): I/O error on POST request for "http://localhost:8888/instances": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused). Further attempts are logged on DEBUG level
`
是我什么参数配置错了吗？我使用的指令是：
`sudo docker run -p 8080:8080 -e MYSQL_URL=127.0.0.1:3306 -e MYSQL_USERNAME=root -e MYSQL_PASSWORD=mysql -e REDIS_HOST=127.0.0.1 -e REDIS_PORT=6379 -e ADMIN_SERVER_URL=http://localhost:8888 -e ADMIN_SERVER_USERNAME=admin -e ADMIN_SERVER_PASSWORD=admin -it registry.cn-beijing.aliyuncs.com/itning/shw_server:latest
`
事实上我使用其他推荐的方法也没能成功运行该项目。

**Comment by itning** [comment]
docker虚拟的一个环境
``ADMIN_SERVER_URL=http://localhost:8888``其中``localhost``的``8888``端口并没有开启ADMIN_SERVER

**Comment by itning** [comment]
> docker虚拟的一个环境
> `ADMIN_SERVER_URL=http://localhost:8888`其中`localhost`的`8888`端口并没有开启ADMIN_SERVER
